server:
  port: 8090
  
spring:
  application:
    name: emp-rest-service
    
eureka:
  client:
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:8761/eureka
      
    
